version: "2.4"

services:
  rails_app_teste:
    container_name: rails_app_teste
    build: .
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: development
    user: "0:0"
    command: bash -c "mkdir -p /usr/local/bundle/ruby/3.2.0/cache && chown -R 1000:1000 /usr/local/bundle && su rails -c 'bundle install && bin/rails db:migrate && bin/rails server -p 3000 -b 0.0.0.0'"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    mem_limit: 2048m

volumes:
  bundle_cache:
